### ISSUE TITLE
Mounts/Companions Buttons

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI_Bunny#11]
Spacing around button is a little off. Is it just me?

My computer is 27 inch iMac - 2560x1440.

![wowscrnshot_090116_120127]
(https://cloud.githubusercontent.com/assets/7307335/18178730/25d670aa-7045-11e6-8dd9-f15ed9e03517.jpg)

![wowscrnshot_090116_120121](https://cloud.githubusercontent.com/assets/7307335/18178725/20437886-7045-11e6-9df8-e0b3653608c4.jpg)

![wowscrnshot_090116_120127 - copy](https://cloud.githubusercontent.com/assets/7307335/18178727/221ac2f4-7045-11e6-8033-d6c5dffbc72d.jpg)

**Comment by crumdidlyumshis** [comment]
If you aren't having this issue, close if needed. Could just be my screen resolution.

**Comment by Bunny67** [comment]
![wowscrnshot_090116_214610](https://cloud.githubusercontent.com/assets/5816685/18180009/ae02a528-708d-11e6-9348-9c778e769918.jpg)

**Comment by crumdidlyumshis** [comment]
Hmm, I don't know. Yours looks correct. :(

**Comment by Bunny67** [comment]
In the screenshot size of 40, it was changed to 36 in the latest update

**Comment by crumdidlyumshis** [comment]
It works! Thanks!
