### ISSUE TITLE
Suggestion - Companions/Mounts

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI_Bunny#13]
Maybe add "Total Mounts" and "Total Companions" above icons.

Also a search filter possible?

Retail

![wowscrnshot_090116_164450 - copy](https://cloud.githubusercontent.com/assets/7307335/18185572/f2371cee-7063-11e6-90ae-2c699f218d13.jpg)

WotLK

![wowscrnshot_090116_164902](https://cloud.githubusercontent.com/assets/7307335/18185601/0ff8af9a-7064-11e6-8446-90cd99429dc2.jpg)

**Comment by Bunny67** [comment]
added in next update

**Comment by crumdidlyumshis** [comment]
did you forget to update? haha :)

**Comment by Bunny67** [comment]
More will update :)
