### ISSUE TITLE
Death recap issues

### ISSUE THREAD

**Issue by Tristan000** [ElvUI-WotLK/ElvUI_Bunny#19]
There are still 2-3 issues. Mostly in battlegrounds.

1) When you die in a bg or instance there is no release timer. Now its shows -1 secs.

2) When you die in a bg and the enemy force release you, the death recap popup stays visible, even if you ressurect.

3) When a bg ends and you are dead, the death recap popup will stay visible after you exit the bg.

**Comment by Loaal** [comment]
Update should fix all 3 issues.

**Comment by Tristan000** [comment]
It seems to be ok now.
