### ISSUE TITLE
animatedLoss error

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI_Bunny#28]
Message: ...AddOns\ElvUI_Bunny\modules\unitframes\unitframes.lua:11: attempt to index field 'animatedLoss' (a nil value)
Time: 01/25/17 22:56:12
Count: 1
Stack: [C]: ?
...AddOns\ElvUI_Bunny\modules\unitframes\unitframes.lua:11: in function <...AddOns\ElvUI_Bunny\modules\unitframes\unitframes.lua:8>
[C]: in function `Configure_HealthBar'
...dOns\ElvUI\modules\unitframes\elements\classbars.lua:224: in function <...dOns\ElvUI\modules\unitframes\elements\classbars.lua:197>
(tail call): ?
...ibraries\oUF_Plugins\oUF_DruidMana\oUF_DruidMana.lua:69: in function <...ibraries\oUF_Plugins\oUF_DruidMana\oUF_DruidMana.lua:26>
...ibraries\oUF_Plugins\oUF_DruidMana\oUF_DruidMana.lua:77: in function `func'
Interface\AddOns\ElvUI\Libraries\oUF\ouf.lua:171: in function `func'
Interface\AddOns\ElvUI\Libraries\oUF\events.lua:123: in function `?'
Interface\AddOns\ElvUI\Libraries\oUF\events.lua:86: in function <Interface\AddOns\ElvUI\Libraries\oUF\events.lua:72>

Locals:

**Comment by Bunny67** [comment]
Test on a different character, since I could not get an error

**Comment by crumdidlyumshis** [comment]
It was a fresh install on Druid. I'll try again later. I'm at work
