### ISSUE TITLE
Character Window Resistance  Problem

### ISSUE THREAD

**Issue by Fillure** [ElvUI-WotLK/ElvUI_Bunny#29]
![unbenannt](https://cloud.githubusercontent.com/assets/25384830/22369126/6eba3c0c-e48a-11e6-89ac-89083372faa7.PNG)
![unbenannt2](https://cloud.githubusercontent.com/assets/25384830/22369142/7f0dc100-e48a-11e6-90ef-ba4368873d26.PNG)

As you can see in the two attached Files the Problem is that the Resistance Part is out of the Character Window and is still shown after closing the Character Window.

**Comment by Bunny67** [comment]
Add to GearScore.toc ## RequiredDeps: ElvUI_Bunny or use GearScore version for 3.3.5
