### ISSUE TITLE
Character Frame - Extended

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI_Bunny#3]
Need to add a script to check when the frame is extended, the other various frames that sit to the right of the character frame are pushed over more.

![wowscrnshot_092315_142700](https://cloud.githubusercontent.com/assets/7307335/10057421/dae41348-6205-11e5-84e5-2f880a9e0313.jpg)

**Comment by Bunny67** [comment]
So far not found a solution to this bug :(

**Comment by crumdidlyumshis** [comment]
Maybe under ElvUI, add a script that checks to see if ElvUI_Bunny is loaded. If so, then check to see if the expanded frame is true or false. If true, then set the necessary frames to re-position themselves to the right of the expanded frame.

Just guessing. I have very little LUA knowledge. I am a PHP, JavaScript/jQuery web developer. Haha :)

**Comment by Bunny67** [comment]
Not so simple :(

**Comment by Bunny67** [comment]
Partially fixed :)

**Comment by crumdidlyumshis** [comment]
omg thank you! <3
