### ISSUE TITLE
Scroll Bar - Size Changes

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI_Bunny#6]
The scrollbar size changes between windows. The spacing between the scrollbars changes too.

![untitled](https://cloud.githubusercontent.com/assets/7307335/13361072/2f122b2a-dc82-11e5-8b2f-4eb4b07d597f.jpg)

**Comment by Bunny67** [comment]
While I do not know because of what is happening. Titles and Equipment must be the same

**Comment by crumdidlyumshis** [comment]
YES! <3
