### ISSUE TITLE
AddOns Menu - Scroll Error

### ISSUE THREAD

**Issue by crumdidlyumshis** [ElvUI-WotLK/ElvUI_Bunny#8]
Message: ...erface\AddOns\ElvUI_Bunny\modules\misc\addonList.lua:156: AddOn index must be in the range of 1 to 82
Time: 05/24/16 21:38:46
Count: 1
Stack: [C]: ?
[C]: in function `GetAddOnInfo'
...erface\AddOns\ElvUI_Bunny\modules\misc\addonList.lua:156: in function `TooltipUpdate'
...erface\AddOns\ElvUI_Bunny\modules\misc\addonList.lua:333: in function <...erface\AddOns\ElvUI_Bunny\modules\misc\addonList.lua:327>
[C]: in function `SetVerticalScroll'
[string "*:OnValueChanged"]:1: in function <[string "*:OnValueChanged"]:1>
[C]: in function `SetValue'
Interface\FrameXML\UIPanelTemplates.lua:163: in function `ScrollFrameTemplate_OnMouseWheel'
[string "*:OnMouseWheel"]:1: in function <[string "*:OnMouseWheel"]:1>

Locals:

**Comment by Apollyonn** [comment]
Delete/commend line 333 in addonList.lua
It seems to fix the problem without breaking anything else.

**Comment by crumdidlyumshis** [comment]
Haven't had this issue since.
