### ISSUE TITLE
Stats - Damage per Second not enough space for dual wielders

### ISSUE THREAD

**Issue by Fluffybully** [ElvUI-WotLK/ElvUI_Bunny#9]
<a href="http://shrani.si/?3c/Zi/3zoMo37Q/dayum.png"><img src="http://shrani.si/t/3c/Zi/3zoMo37Q/dayum.jpg" style="border: 0px;" alt="Shrani.si"/></a>

As you can see on the screenshot. The damage per second values don't have enough space for themselves therefore they override they text it self.

**Comment by crumdidlyumshis** [comment]
I shall try it out and see. Good point, could be cause of font too. That font looks large. Also, future reference, you can just drag and drop the image to the markdown editor and it will upload automatically :+1:

**Comment by Fluffybully** [comment]
Any update on that?

**Comment by Bunny67** [comment]
I do not see a solution to this bug.
The positions and size of the text has not been changed

**Comment by crumdidlyumshis** [comment]
@Bunny67 How about renaming "Damage Per Second" to "DPS"?

**Comment by Bunny67** [comment]
Yes
So it should be, a little later fix
